/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.admin;

import java.awt.event.ActionListener;

import java.awt.event.WindowListener;

/**
 *
 * @author SystemX
 */
public class FrmListOfInvoiceA extends javax.swing.JDialog {

    /**
     * Creates new form FrmListOfInvoice
     */
    public FrmListOfInvoiceA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaNarudzbi = new javax.swing.JTable();
        btnObrisiNarudzbu = new javax.swing.JButton();
        btnDetaljanPrikaz = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblListaNarudzbi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaNarudzbi);

        btnObrisiNarudzbu.setText("Obrisi narudzbu");

        btnDetaljanPrikaz.setText("Detalji narudzbe");

        btnClose.setText("Zatvori");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnObrisiNarudzbu)
                .addGap(34, 34, 34)
                .addComponent(btnDetaljanPrikaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiNarudzbu)
                    .addComponent(btnDetaljanPrikaz)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDetaljanPrikaz;
    private javax.swing.JButton btnObrisiNarudzbu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaNarudzbi;
    // End of variables declaration//GEN-END:variables

    public void addBtnObrisiNarudzbaActionListener(ActionListener actionListener) {
        btnObrisiNarudzbu.addActionListener(actionListener);
    }
    
    public void addBtnCancelNarudzbaActionListener(ActionListener actionListener) {
        btnClose.addActionListener(actionListener);
    }
    
    public void addBtnDetaljiNarudzbaActionListener(ActionListener actionListener) {
        btnDetaljanPrikaz.addActionListener(actionListener);
    }
    
    public javax.swing.JTable getTblListaNarudzbi() {
        return tblListaNarudzbi;
    }
    
    public void addWindowOpenedListener(WindowListener windowListener) {
        this.addWindowListener(windowListener);
    }
}
