/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.admin;


import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author SystemX
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        btnCharBar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoiceItem = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNewProduct = new javax.swing.JMenuItem();
        jMenuShowProducts = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miListaNarudzbi = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miNoviDobavljac = new javax.swing.JMenuItem();
        miListaDobavljaca = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miNoviProizvodjac = new javax.swing.JMenuItem();
        miListaProizvodjaca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogOut.setText("Logout");

        btnCharBar.setText("Chart Bar");

        tblInvoiceItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInvoiceItem);

        jMenu1.setText("Proizvod");

        jMenuNewProduct.setText("Novi proizvod");
        jMenuNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNewProductActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNewProduct);

        jMenuShowProducts.setText("Lista proizvoda");
        jMenu1.add(jMenuShowProducts);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Narudzba");

        miListaNarudzbi.setText("Lista narudzbi");
        jMenu2.add(miListaNarudzbi);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dobavljac");

        miNoviDobavljac.setText("Novi dobavljac");
        jMenu3.add(miNoviDobavljac);

        miListaDobavljaca.setText("Lista dobavljaca");
        jMenu3.add(miListaDobavljaca);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Proizvodjac");

        miNoviProizvodjac.setText("Novi proizvodjac");
        jMenu4.add(miNoviProizvodjac);

        miListaProizvodjaca.setText("Lista proizvodjaca");
        jMenu4.add(miListaProizvodjaca);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCharBar)
                        .addGap(25, 25, 25)
                        .addComponent(btnLogOut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCharBar)
                    .addComponent(btnLogOut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNewProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNewProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharBar;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuNewProduct;
    private javax.swing.JMenuItem jMenuShowProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miListaDobavljaca;
    private javax.swing.JMenuItem miListaNarudzbi;
    private javax.swing.JMenuItem miListaProizvodjaca;
    private javax.swing.JMenuItem miNoviDobavljac;
    private javax.swing.JMenuItem miNoviProizvodjac;
    private javax.swing.JTable tblInvoiceItem;
    // End of variables declaration//GEN-END:variables

    public void btnJMenuNewProduct(ActionListener actionListener) {
        jMenuNewProduct.addActionListener(actionListener);
    }
    
    public void btnJMenuShowProducts(ActionListener actionListener) {
        jMenuShowProducts.addActionListener(actionListener);
    }
    
    public void btnListaNarudzbi(ActionListener actionListener) {
        miListaNarudzbi.addActionListener(actionListener);
    }
    
    public void btnNoviDobavljac(ActionListener actionListener) {
        miNoviDobavljac.addActionListener(actionListener);
    }
    
    public void btnListaDobavljaca(ActionListener actionListener) {
        miListaDobavljaca.addActionListener(actionListener);
    }
    
    public void btnNoviProizvodjac(ActionListener actionListener) {
        miNoviProizvodjac.addActionListener(actionListener);
    }
    
    public void btnListaProizvodjaca(ActionListener actionListener) {
        miListaProizvodjaca.addActionListener(actionListener);
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }
    
   
    
    public void addWindowListeneronClosed(WindowListener windowListener) {
        this.addWindowListener(windowListener);
    }
    
    public void addWindowListeneronOpened(WindowListener windowListener) {
        this.addWindowListener(windowListener);
    }

    public JButton getBtnCharBar() {
        return btnCharBar;
    }
     public void btnBarChart(ActionListener actionListener) {
        btnCharBar.addActionListener(actionListener);
    }

    public JTable getTblInvoiceItem() {
        return tblInvoiceItem;
    }
    
    
}
